# Generated by Django 4.2 on 2023-04-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(max_length=100)),
                ('millati', models.CharField(max_length=50)),
                ('yoshi', models.FloatField()),
                ('gruppasi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FISH', models.CharField(max_length=100)),
                ('birthdate', models.DateField()),
                ('birthplace', models.CharField(max_length=100)),
                ('millati', models.CharField(max_length=50)),
                ('unvoni', models.CharField(choices=[('Direktor', 'Direktor'), ("Katta o'qituvchi", "Katta o'qituvchi"), ('Oshpaz', 'Oshpaz'), ('Qorovul', 'Qorovul'), ("Kichik o'qituvchi", "Kichik o'qituvchi")], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('davomiyligi', models.FloatField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kd.staff')),
            ],
        ),
    ]
